apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot-api-deployment
  labels:
    app: telegram-bot-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telegram-bot-api
  template:
    metadata:
      labels:
        app: telegram-bot-api
    spec:
      containers:
      - name: telegram-bot-api
        image: nicopaez/telegrambot:0.0.7
        ports:
        - containerPort: 8080
        env:
        - name: TELEGRAM_TOKEN
          value: "A_COMPLETAR"
